version: '3.9'
services:
  node-server:
    build: 
      context: 003-es-module
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # 5000 is the port of the container, 5000 is the port of the host
      